apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: namespace
    fieldPath: data.namespace
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.name
  - select:
      kind: Capacity
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: NFDeployment
    fieldPaths:
    - metadata.namespace
  - select:
      kind: NFConfig
    fieldPaths:
    - metadata.namespace
  - select:
      kind: NetworkAttachmentDefinition
    fieldPaths:
    - metadata.namespace