apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: example-n4
  namespace: smf-example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "example",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "ens9f1",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
  