apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: example
  namespace: smf-example
spec:
  provider: smf.openairinterface.org
  capacity:
    maxNFConnections: 5
    maxSessions: 500
  interfaces:
  - name: n4
    ipv4:
      address: 10.104.50.233/29 # kpt-set: ${n4-address}
      gateway: 10.104.50.236  # kpt-set: ${n4-gateway}
    vlanID: 4
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  parametersRefs:
  - name: oai-smf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig