apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-core-n2
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-core-n2",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens9f1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "routes": [
              {
                "dst": "10.0.22.0/24",
                "gw": "10.0.22.1"
              }
            ]
      }
    }
                ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-core-f1c
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-core-f1c",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens9f1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "routes": [
              {
                "dst": "10.100.50.233/29",
                "gw": "10.100.50.236"
              }
            ]
      }
    }
                ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-core-e1
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-core-e1",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens9f1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "routes": [
              {
                "dst": "10.101.50.233/29",
                "gw": "10.101.50.236"
              }
            ]
      }
    }
                  ]
    }