apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-edge-n2
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-edge-n2",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens3f0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
                ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-edge-f1c
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-edge-f1c",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens3f0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
                ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-edge-e1
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-edge-e1",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens3f0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
                  ]
    }