apiVersion: v1
kind: Service
metadata:
  name: oai-nrf
  namespace: oai-core
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.nephio.org/oai: nrf
  type: ClusterIP