apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /oai-ue
  name: oai-ue
  labels:
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/enforce: "privileged"