apiVersion: v1
kind: Namespace
metadata:
  name: oai-ran-operators
  labels:
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/enforce: "privileged"
