apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: amf-example
  namespace: amf-example
spec:
  provider: amf.openairinterface.org
  capacity:
    maxSubscribers: 1000
  interfaces:
  - name: n2
    ipv4:
      address: 10.0.22.101/24
      gateway: 10.0.22.1
    vlanID: 2
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  parametersRefs:
  - name: oai-amf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig