apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: oai-operators-up
spec:
  upstream:
    repo: nephio-oai-rke-packages
    package: oai-up-operators
    revision: main
  downstream:
    repo: rke-mgmt
    package: oai-up-operators
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core