apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: smf-core-n4
  namespace: smf-example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "smf-core-n4",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "ens9f1",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [
            { 
              "dst": "10.0.22.0/24", 
              "gw": "10.0.22.1" 
            }
            ]

          }
        }
      ]
    }
  