apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-cni-plugins-install
spec:
  upstream:
    repo: nephio-oai-rke-packages
    package: infra-setup/cni-plugins-install
    revision: main
  downstream:
    repo: rke-edge
    package: cni-plugins-install
  annotations:
    approval.nephio.org/policy: initial
