apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oai-operators-ran
spec:
  upstream:
    repo: nephio-oai-rke-packages
    package: oai-ran-operators
    revision: main
  downstream:
    repo: rke-edge
    package: oai-ran-operators
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge