apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: oai-ue-orange-4
spec:
  upstream:
    repo: nephio-oai-rke-packages
    package: oai-nr-ue-custom
    revision: main
  downstream:
    repo: rke-edge
    package: oai-ue-orange-4

  injectors:
  - name: edge
  annotations:
    approval.nephio.org/policy: initial
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/starlark:v0.5.0
      configMap:
             source: |
                def mutate(config):
                    config['data']['dnn'] = 'orange'
                    config['data']['fullImsi'] = '208990100001132'
                    config['data']['nssaiSd'] = '16777215'
                    config['data']['nssaiSst'] = '1'
                    config['data']['rfSimulator'] = 'oai-gnb-du.oai-ran-du'

                res = ctx.resource_list["items"]
                for r in res:
                  if (r["kind"] == "ConfigMap") and (r["metadata"]["name"] != "kptfile.kpt.dev"):
                    mutate(r)
   