apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oai-upf-3
spec:
  upstream:
    repo: nephio-oai-rke-packages
    package: oai-upf-custom
    revision: main
  downstream:
    repo: rke-edge
    package: oai-upf-3
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge
  pipeline:
    mutators:
      - image: gcr.io/kpt-fn/apply-setters:v0.2.0
        configMap:
          plmn-info: |-
            - plmnID:
                mcc: "208"
                mnc: "99"
              tac: 1
              nssai:
                - sst: 1
                  sd: ffffff
                  dnnInfo:
                    - name: ooredoo
                      sessionType: ipv4
                      dns: 8.8.8.8
                      subnet: 10.3.0.0/24
          n3-address: 10.103.50.237/29
          n3-gateway: 10.103.50.236        
          n4-address: 10.104.50.237/29
          n4-gateway: 10.104.50.236
          n6-address: 10.0.22.117/24
          n6-gateway: 10.0.22.1