apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: WorkloadCluster #ConfigMap #
    name:  package-path #kptfile.kpt.dev
    fieldPath: spec.clusterName #data.package-path
  targets:
  - select:
      kind: NFDeployment
    fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
      index: 1
  - select:
      kind: NFConfig
    fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
      index: 0
  - select:
      kind: NetworkAttachmentDefinition
    fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
      index: 1
  - select:
      kind: Capacity
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/owner]
    options:
      delimiter: '-'
      index: 1
