apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n3.example
  namespace: upf-example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "example",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens3f0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n4.example
  namespace: upf-example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "example",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens3f0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
                ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n6.example
  namespace: upf-example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "example",
      "plugins": [
    {
      "type": "macvlan",
      "capabilities": {
        "ips": true
      },
      "master": "ens3f0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.0.22.1"
              }
            ]
      }
    }
     ]
    }
