apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: NF-example
  namespace: upf-example
spec:
  provider: upf.openairinterface.org
  capacity:
    maxDownlinkThroughput: 5G
    maxUplinkThroughput: 5G
  parametersRefs:
  - name: oai-upf2-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  interfaces:
  - name: n3
    ipv4:
      address: 10.103.50.235/29 # kpt-set: ${n3-address}
      gateway: 10.103.50.236 # kpt-set: ${n3-gateway}
    vlanID: 3
  - name: n4
    ipv4:
      address: 10.104.50.235/29 # kpt-set: ${n4-address}
      gateway: 10.104.50.236 # kpt-set: ${n4-gateway}
    vlanID: 4
  - name: n6
    ipv4:
      address: 10.0.22.116/24 # kpt-set: ${n6-address}
      gateway: 10.0.22.1 # kpt-set: ${n6-gateway}
    vlanID: 6
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  - name: vpc-internet
    interfaces:
    - n6
  - name: vpc-ran
    interfaces:
    - n3
