apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: upsert-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
source: |-
        res = ctx.resource_list["items"]
        for r in res:
          if r["metadata"]["name"] == "kptfile.kpt.dev"
            create_ns = r["spec"]["data"]["create_ns"]
            break
        for r in res:
          if (r["kind"] == "Namespace"):  
            ns = r 
            break
        if not bool(create_ns):
          res.remove(ns)   