apiVersion: v1
kind: Secret
metadata: # kpt-merge: gitea/gitea-postgresql
  name: gitea-postgresql
  namespace: gitea
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: gitea
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|gitea|gitea-postgresql'
type: Opaque
data:
  postgres-password: c2VjcmV0
  password: c2VjcmV0
