apiVersion: v1
kind: Service
metadata: # kpt-merge: gitea/gitea-memcached
  name: gitea-memcached
  namespace: gitea
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: gitea
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|gitea|gitea-memcached'
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: memcache
      port: 11211
      targetPort: memcache
      nodePort: null
  selector:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: gitea
