apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: cuup-example
  namespace: example
spec:
  provider: cuup.openairinterface.org
  interfaces:
  - name: n3
    ipv4:
      address: 10.0.22.113/24 
      gateway: 10.0.22.1
    vlanID: 3
  - name: f1u
    ipv4:
      address: 10.100.50.234/29
      gateway: 10.100.50.236
    vlanID: 32
  - name: e1
    ipv4:
      address: 10.101.50.234/29
      gateway: 10.101.50.236
    vlanID: 33
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n3
  - name: vpc-cudu-f1
    interfaces:
    - f1u
  - name: vpc-cu-e1
    interfaces:
    - e1
  parametersRefs:
  - name: oai-cuup-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  - apiVersion: ref.nephio.org/v1alpha1
    kind: Config
    name: oai-cucp-config